language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # PyPy versions
  - "pypy"
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"
# command to install dependencies
install:
  - pip install .
  - pip install codecov
# command to run tests
script: 
  - coverage run -m unittest discover

# upload coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)